-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Goal CASCADE;
DROP TABLE IF EXISTS Friendship CASCADE;
DROP TABLE IF EXISTS Workout CASCADE;
DROP TABLE IF EXISTS CardioExercise CASCADE;
DROP TABLE IF EXISTS WeightExercise CASCADE;
DROP TABLE IF EXISTS ExerciseSet CASCADE;

